name: Issue
description: Create an issue.
title: "[Issue]: "
type: "Task"
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What is the task to be developed?
      placeholder: Be clear and detailed about what developers should do!
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: What will mean the issue is complete?
      placeholder: Provide concrete and concise points!
      value: |
        []
        []
        []
        ...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/hack4impact/.github/blob/main/docs/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
