name: Issue
description: Create an issue.
title: "[Issue]: "
type: "Task"
body:
  - type: input
    id: branch
    attributes:
      label: Branch Name
      description: Remember to follow [branch naming convention](https://www.hack4impact.org).
      placeholder: (featurer|fix)/issue_number-branch-name
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What is the task to be developed?
      placeholder: Be clear and detailed about what developers should do!
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: What will mean the issue is complete?
      placeholder: Provide concrete and concise points!
      value: |
        - [ ] TODO: Add acceptance criteria
        - [ ] TODO: Add acceptance criteria
        - [ ] TODO: Add acceptance criteria
        ...
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure you do all this before you create the issue.
      options:
        - label: I have checked for duplicate issues.
          required: true
        - label: I have assigned the issue to the correct project board.
          required: true
        - label: I have tagged the issue properly.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/hack4impact/.github/blob/main/docs/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
